export const CONTACT_FORM_LABELS = {
  en: {
    name: "Name",
    namePlaceholder: "Your name",
    email: "Email",
    emailPlaceholder: "you@example.com",
    subject: "Subject",
    subjectPlaceholder: "Select a subject",
    message: "Message",
    messagePlaceholder: "Write your message...",
    sending: "Sending...",
    send: "Send Message",
    success: "Message sent! I'll get back to you soon.",
    deliveryIssue: "Failed to send. Please email me directly at daniel@malmqvist.dev",
    subjectConsulting: "Consulting",
    subjectInquiry: "Job Inquiry",
    subjectCollab: "Collaboration",
    subjectGeneral: "General",
  },
  ja: {
    name: "お名前",
    namePlaceholder: "お名前",
    email: "メールアドレス",
    emailPlaceholder: "you@example.com",
    subject: "件名",
    subjectPlaceholder: "件名を選択",
    message: "メッセージ",
    messagePlaceholder: "メッセージを入力してください...",
    sending: "送信中...",
    send: "送信する",
    success: "メッセージを送信しました。折り返しご連絡いたします。",
    deliveryIssue: "送信に失敗しました。daniel@malmqvist.dev まで直接ご連絡ください。",
    subjectInquiry: "採用お問い合わせ",
    subjectConsulting: "コンサルティング",
    subjectCollab: "コラボレーション",
    subjectGeneral: "その他",
  },
  sv: {
    name: "Namn",
    namePlaceholder: "Ditt namn",
    email: "E-post",
    emailPlaceholder: "du@exempel.se",
    subject: "Ämne",
    subjectPlaceholder: "Välj ett ämne",
    message: "Meddelande",
    messagePlaceholder: "Skriv ditt meddelande...",
    sending: "Skickar...",
    send: "Skicka meddelande",
    success: "Meddelandet skickades! Jag återkommer snart.",
    deliveryIssue: "Det gick inte att skicka. Mejla mig direkt på daniel@malmqvist.dev",
    subjectInquiry: "Jobbförfrågan",
    subjectConsulting: "Konsultförfrågan",
    subjectCollab: "Samarbete",
    subjectGeneral: "Allmänt",
  },
} as const;
